"use client";
import { useState } from "react";
import { CheckCircle, CalendarDays, Mail, ClipboardList, PhoneCall, ShoppingCart, Sparkles, ShieldCheck, Workflow, ArrowRight, Clock, Star, Facebook, Instagram, Youtube } from "lucide-react";

export default function Page() {
  const [submitted, setSubmitted] = useState(false);

  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-50 to-white text-slate-900">
      <header className="sticky top-0 z-40 bg-white/80 backdrop-blur border-b">
        <div className="max-w-6xl mx-auto px-4 py-3 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Sparkles className="h-6 w-6" />
            <span className="font-bold text-xl">TaskTamer</span>
            <span className="text-sm text-slate-500 ml-2">All-In-One Life Management</span>
          </div>
         <nav className="hidden md:flex items-center gap-6 text-sm">
  <a href="/services" className="hover:text-slate-700">Services</a>
  <a href="/packages" className="hover:text-slate-700">Packages</a>
  <a href="/process" className="hover:text-slate-700">How it Works</a>
  <a href="/about" className="hover:text-slate-700">About</a>
  <a href="/reviews" className="hover:text-slate-700">Reviews</a>
  <a href="/contact" className="hover:text-slate-700">Contact</a>
</nav>


        </div>
      </header>

      <section className="relative overflow-hidden">
        <div className="max-w-6xl mx-auto px-4 pt-16 pb-12 grid md:grid-cols-2 gap-10 items-center">
          <div>
            <h1 className="text-4xl md:text-5xl font-extrabold leading-tight tracking-tight">
              Calm for busy lives.
              <br />
              <span className="text-slate-600">Take a breath — I got it.</span>
            </h1>
            <p className="mt-4 text-slate-600 text-lg">
              Inbox tamed. Schedules set. Lists handled. TaskTamer gives you clear days and quiet headspace, without hiring a full-time assistant.
            </p>
            <div className="mt-6 flex flex-wrap gap-3">
              <a href="#packages"><button className="rounded-2xl px-5 py-3 bg-slate-900 text-white">See packages</button></a>
              <a href="#contact"><button className="rounded-2xl px-5 py-3 border">Get started</button></a>
            </div>
          </div>

          <div className="md:pl-8">
            <div className="shadow-xl rounded-3xl border bg-white">
              <div className="p-6 border-b">
                <h3 className="font-semibold text-lg">Your day, organized</h3>
                <p className="text-slate-500">Sample daily plan generated by TaskTamer</p>
              </div>
              <div className="p-6 space-y-3">
                {[
                  { t: "Review & triage 120 emails", i: Mail },
                  { t: "Schedule pediatric visit + hair appt", i: CalendarDays },
                  { t: "Prepare grocery list + Instacart notes", i: ShoppingCart },
                  { t: "Draft client call script + follow-ups", i: PhoneCall },
                  { t: "Update tasks in Notion + reminders", i: ClipboardList },
                ].map((row, idx) => (
                  <div key={idx} className="flex items-center gap-3">
                    <row.i className="h-5 w-5 text-slate-700" />
                    <span className="text-slate-700">{row.t}</span>
                    <CheckCircle className="ml-auto h-5 w-5 text-emerald-500" />
                  </div>
                ))}
              </div>
            </div>
          </div>

        </div>
      </section>

      <section id="services" className="py-16 bg-white">
        <div className="max-w-6xl mx-auto px-4">
          <h2 className="text-3xl font-bold">Services</h2>
          <p className="mt-2 text-slate-600">Professional help with a small-business heart.</p>

          <div className="mt-8 grid md:grid-cols-3 gap-6">
            {[
              { icon: Mail, title: "Email Management", desc: "Clean, organize, and follow up so your inbox finally breathes." },
              { icon: CalendarDays, title: "Scheduling", desc: "Appointments, reminders, and planning handled for you." },
              { icon: ClipboardList, title: "Task Systems", desc: "Custom planners and workflows that keep life flowing." },
              { icon: ShoppingCart, title: "Lists & Shopping", desc: "Groceries, errands, and supplies tracked & managed." },
              { icon: PhoneCall, title: "Scripts & Templates", desc: "Polished phone scripts, messages, and more." },
              { icon: Workflow, title: "Admin Help", desc: "Data entry, organization, cleanup, research, and more." },
            ].map((s, i) => (
              <div key={i} className="rounded-3xl border p-6 bg-white">
                <s.icon className="h-6 w-6" />
                <h3 className="font-semibold text-lg mt-3">{s.title}</h3>
                <p className="text-slate-600 mt-2">{s.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section id="process" className="py-16 bg-slate-50">
        <div className="max-w-6xl mx-auto px-4">
          <h2 className="text-3xl font-bold">How it works</h2>
          <div className="mt-8 grid md:grid-cols-3 gap-6">
            {["Tell me what’s noisy", "I organize it", "You get your time back"].map((step, i) => (
              <div key={i} className="rounded-3xl border p-6 bg-white">
                <h3 className="font-semibold text-lg">Step {i + 1}</h3>
                <p className="mt-2 text-slate-700">{step}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section id="contact" className="py-16 bg-white">
        <div className="max-w-6xl mx-auto px-4">
          <h2 className="text-3xl font-bold">Get Started</h2>
          <p className="mt-2 text-slate-600">Send a message and I’ll get back to you within 24 hours.</p>

          <form
            className="mt-8 max-w-xl space-y-4"
            action="https://formspree.io/f/your-id"
            method="POST"
            onSubmit={() => setSubmitted(true)}
          >
            <input name="name" required placeholder="Your name" className="w-full border rounded-xl px-3 py-2" />
            <input type="email" name="email" required placeholder="Email" className="w-full border rounded-xl px-3 py-2" />
            <textarea name="message" required placeholder="Tell me what you need help with" rows={5} className="w-full border rounded-xl px-3 py-2" />

            {!submitted ? (
              <button className="rounded-2xl px-4 py-2 bg-slate-900 text-white" type="submit">
                Send <ArrowRight className="inline-block ml-2 h-4 w-4" />
              </button>
            ) : (
              <span className="text-emerald-600 flex items-center gap-2 mt-2">
                <CheckCircle className="h-5 w-5" /> Message sent!
              </span>
            )}
          </form>
        </div>
      </section>
<footer className="py-10 bg-slate-50 border-t">
  <div className="max-w-6xl mx-auto px-4 flex items-center justify-between">
    <p className="text-sm text-slate-600">
      © {new Date().getFullYear()} TaskTamer. All rights reserved.
    </p>

    <p className="text-sm">
      Contact:
      <a 
        href="mailto:tasktamerhelp@gmail.com" 
        className="text-pink-600 hover:underline ml-1"
      >
        tasktamerhelp@gmail.com
      </a>
    </p>
  </div>
</footer>

    </div>
  );
}
